In [1]:
import syft as sy

ModuleNotFoundError: No module named 'syft'

In [2]:
esf = sy.login(url="http://172.20.58.251:8081/", email="info@openmined.org", password="changethis")


Anyone can login as an admin to your node right now because your password is still the default PySyft username and password!!!

Connecting to http://172.20.58.251:8081/... done! 	 Logging into esf... done!


In [3]:
esf.users

In [4]:
esf.users.create(
    **{
        "name": "zetyun_psi",
        "email": "sample2@zetyun.com",
        "password": "zetyun",
        "budget":200
    }
)

In [5]:
esf.users

In [6]:
import load

ids = load.load_column("dataset/esf.csv", "id", "str")

values = load.load_column("dataset/esf.csv", "value", "float")

------------------------dataset/esf.csv------------------------
                                 id  value
0  60dcd6597ac34d97aa2fc913b95009c4    522
1  ace97a31c0b34c6cafc8c6cbb76ff49c    643
2  518b5db5bfc14ecb8bf921c5b417b7c2    570
3  e3071268cd964a258bced22b36f98f79    365
4  01e95a079e9040db8be63d2cfea342e4    824
------------------------id------------------------
array([  450007691, -1643464018,  -956291306, -1892816489,   466742559])
------------------------dataset/esf.csv------------------------
                                 id  value
0  60dcd6597ac34d97aa2fc913b95009c4    522
1  ace97a31c0b34c6cafc8c6cbb76ff49c    643
2  518b5db5bfc14ecb8bf921c5b417b7c2    570
3  e3071268cd964a258bced22b36f98f79    365
4  01e95a079e9040db8be63d2cfea342e4    824
------------------------value------------------------
array([522, 643, 570, 365, 824])


In [7]:
esf.load_dataset(
    assets={
        "esf_id": sy.Tensor(ids).private(min_val=float(ids.min()), max_val=float(ids.max()), entities="老赖数据:esf:id"),
        "esf_value": sy.Tensor(values).private(min_val=float(values.min()), max_val=float(values.max()), entities="老赖数据:esf:values")
    },
    name="esf",
    description="老赖数据:esf"
)

Loading dataset... uploading... SUCCESS!                                                                                                                                      

Run <your client variable>.datasets to see your new dataset loaded into your machine!


In [8]:
id_ptr = esf.datasets[0]["esf_id"]
print(id_ptr)

array([-841309539,  623975884, -778703461, ..., 1508312900, 1152483359,
        -34168510])

 (The data printed above is synthetic - it's an imitation of the real data.)


In [9]:
id_ptr.request(reason="需要获取准确数据, 准备求交")

In [10]:
[x for x in esf.requests.requests if x.request_description == "需要获取准确数据, 准备求交"][0].accept()

In [11]:
esf_id_tensor = id_ptr.get(delete_obj=False)
esf_id_tensor

Tensor(child=SingleEntityPhiTensor(entity=老赖数据:esf:id, child=[  450007691 -1643464018  -956291306 ...   266749272 -1085474894
  -585203823]))

In [12]:
server_items = [str(i) for i in esf_id_tensor.child.child.tolist()]

In [13]:
len(server_items)

5000

In [14]:
import inter

psi_server = inter.PsiServer("2nd", esf, True, server_items)

In [15]:
psi_server.setup()

1. 等待客户端发送 client_items_len
2. 服务端获取 client_items_len
3. 服务端创建 setup
4. 同意客户端获取 setup


In [16]:
esf.store

[array([726, 987, 725, ..., 272, 459, 289])

 (The data printed above is synthetic - it's an imitation of the real data.), array([    1834905,  1442796991,    60424854, ..., -1009805681,
       -1820144966,   291832685])

 (The data printed above is synthetic - it's an imitation of the real data.), <IntPointer -> esf:d883538fb4c54063ab16af99ac2dbb10>, <ListPointer -> esf:a6bfc5175f9546bf8d19d2d4b98c6cb9>, <ListPointer -> esf:48c03106ae4648c888693bc43b3f2155>]

In [16]:
psi_server.process_request()

1. 等待客户端发起 request
2. 服务端获取 request
3. 处理 request
4. 同意客户端获取 response


In [17]:
esf.store

[array([902, 290, 697, ..., 409, 556, 949])

 (The data printed above is synthetic - it's an imitation of the real data.), array([ 1418459821,   738904277, -1410832857, ...,   925725523,
        1561363760,  1685519011])

 (The data printed above is synthetic - it's an imitation of the real data.), <IntPointer -> esf:8abb56b477cb49aea5616bba9c6da908>, <ListPointer -> esf:1a6bda5c308b428087eeaa38ccd9d275>, <ListPointer -> esf:2998d9e0c97c484bad517d38523444d4>, <ListPointer -> esf:07390f0bd4074293bc403a90dbd4ce57>, <ListPointer -> esf:6dc91b0858064227a367c5c3e067a206>]

In [18]:
esf_value_ptr = esf.datasets[0]["esf_value"]
esf_value_ptr

array([348, 571, 582, ..., 386, 380, 732])

 (The data printed above is synthetic - it's an imitation of the real data.)

In [19]:
esf_value_ptr.request(reason="获取esf_value")
[x for x in esf.requests.requests if x.request_description == "获取esf_value"][0].grant()

In [20]:
esf_value_tensor = esf_value_ptr.get(delete_obj=False)
esf_value = esf_value_tensor.child.child
type(esf_value)

numpy.ndarray

In [21]:
[x for x in esf.store.store if "intersected_items2" in x.tags][0].request(reason="获取求交后的id列表")

In [22]:
[x for x in esf.requests.requests if x.request_description == "获取求交后的id列表"][0].accept()
intersected_items2 = [x for x in esf.store.store if "intersected_items2" in x.tags][0].get(delete_obj=True)
print(intersected_items2[0:5])

['450007691', '466742559', '-1557623790', '-1585423580', '-1966399277']


In [23]:
sub_positions = []
inter_set = set(intersected_items2)
for index, value in enumerate(ids):
    if str(value) in inter_set:
        sub_positions.append(index)

sub_positions

[0,
 4,
 6,
 9,
 11,
 13,
 17,
 19,
 20,
 25,
 30,
 33,
 34,
 42,
 45,
 46,
 47,
 48,
 52,
 53,
 54,
 56,
 59,
 64,
 65,
 70,
 78,
 91,
 94,
 96,
 98,
 101,
 104,
 105,
 107,
 122,
 127,
 153,
 155,
 162,
 163,
 164,
 167,
 175,
 176,
 181,
 186,
 204,
 211,
 215,
 220,
 227,
 228,
 237,
 239,
 241,
 250,
 251,
 255,
 257,
 260,
 264,
 272,
 273,
 275,
 280,
 281,
 283,
 286,
 287,
 293,
 297,
 300,
 301,
 303,
 310,
 314,
 319,
 323,
 325,
 326,
 333,
 334,
 340,
 346,
 351,
 370,
 371,
 372,
 379,
 383,
 387,
 391,
 393,
 400,
 402,
 403,
 412,
 414,
 419,
 422,
 424,
 428,
 431,
 433,
 436,
 438,
 439,
 442,
 444,
 445,
 447,
 448,
 450,
 451,
 453,
 456,
 457,
 468,
 486,
 492,
 495,
 496,
 498,
 507,
 508,
 512,
 514,
 517,
 523,
 525,
 526,
 527,
 532,
 533,
 541,
 548,
 550,
 553,
 560,
 562,
 566,
 567,
 571,
 574,
 595,
 600,
 605,
 619,
 621,
 623,
 629,
 630,
 636,
 646,
 651,
 669,
 673,
 678,
 686,
 688,
 689,
 694,
 696,
 697,
 699,
 706,
 708,
 720,
 725,
 727,
 728,
 73

In [24]:
sub_matrix = []
for i in range(len(intersected_items2)):
    line = []
    for j in range(len(ids)):
        if j == sub_positions[i]:
            line.append(1)
        else:
            line.append(0)
    sub_matrix.append(line)

In [25]:
import numpy as np
esf_slice = np.array(sub_matrix) @ esf_value * 100

In [26]:
# print(np.array(sub_matrix))
# print(type(esf_slice))
print(esf_slice.shape)
print(esf_slice[0:5])

(1259,)
[52200 82400 46200 69700 23700]


In [27]:
zetyun = sy.login(url="http://172.20.58.96:8081/", email="sample3@zetyun.com", password="zetyun")

Connecting to http://172.20.58.96:8081/... done! 	 Logging into zetyun... done!


In [28]:
esf.store

[array([ 259678854,  439904075,  330726701, ..., -380541824,   -5986982,
       1035640812])

 (The data printed above is synthetic - it's an imitation of the real data.), <IntPointer -> esf:8abb56b477cb49aea5616bba9c6da908>, <ListPointer -> esf:1a6bda5c308b428087eeaa38ccd9d275>, <ListPointer -> esf:2998d9e0c97c484bad517d38523444d4>, <ListPointer -> esf:07390f0bd4074293bc403a90dbd4ce57>, array([ 37, 810, 912, ..., 811, 462, 995])

 (The data printed above is synthetic - it's an imitation of the real data.)]

In [30]:
zetyun_slice_ptr = [x for x in esf.store.store if "zetyun_slice" in x.tags][0]

In [31]:
sy.Tensor(esf_slice).send(esf, pointable=True, tags=["esf_slice"], description="esf_slice")

<TensorPointer -> esf:3a66df06034947d9b8bd6b8cf301849a>

In [32]:
esf_slice_ptr = [x for x in esf.store.store if "esf_slice" in x.tags][0]

In [33]:
from syft.core.tensor.smpc.mpc_tensor import MPCTensor

mpc_1 = MPCTensor(shape=esf_slice_ptr.public_shape, parties=[esf, zetyun], secret=esf_slice_ptr)


[2021-12-31T16:59:15.246117+0800][CRITICAL][logger]][3868] 'Class' object has no attribute 'generate_przs'
[2021-12-31T16:59:18.568980+0800][CRITICAL][logger]][3868] 'Class' object has no attribute 'generate_przs'


In [34]:
mpc_2 = MPCTensor(shape=zetyun_slice_ptr.public_shape, parties=[esf, zetyun], secret=zetyun_slice_ptr)

[2021-12-31T16:59:39.494338+0800][CRITICAL][logger]][3868] 'Class' object has no attribute 'generate_przs'
[2021-12-31T16:59:39.960663+0800][CRITICAL][logger]][3868] 'Class' object has no attribute 'generate_przs'


In [35]:
mpc = mpc_1 + mpc_2

In [36]:
mpc.shape

(1259,)

In [37]:
result = mpc.block.reconstruct()

In [38]:
result[0:5]

array([ 139589, 8862292,   95339, 9534583,   29150])

In [39]:
sum = (result * 0.01).sum()
sum

17947172.32

In [40]:
mean = sum / len(intersected_items2)
mean

14255.10112787927

In [47]:
published_result = mpc.publish(sigma=10)

KeyboardInterrupt: 

In [61]:
# published_result.get()
type(published_result)

syft.proxy.syft.lib.python.FloatPointer