In [1]:
import syft as sy

In [2]:
zetyun = sy.login(url="http://172.20.58.96:8081/", email="info@openmined.org", password="changethis")



Anyone can login as an admin to your node right now because your password is still the default PySyft username and password!!!

Connecting to http://172.20.58.96:8081/... done! 	 Logging into zetyun... done!


In [3]:
import load

ids = load.load_column("dataset/zetyun.csv", "id", "str")

values = load.load_column("dataset/zetyun.csv", "value", "float")



------------------------dataset/zetyun.csv------------------------
                                 id name     value
0  60dcd6597ac34d97aa2fc913b95009c4  李八搜    873.89
1  537807d539d74d23a497cf7e80b75afa  王三于  15462.63
2  ace97a31c0b34c6cafc8c6cbb76ff49c  吴九引     97.67
3  b01d7b6de97b43eb82ee759da3397852  孙一捷     79.97
4  518b5db5bfc14ecb8bf921c5b417b7c2  吴一捷    782.58
------------------------id------------------------
array([  450007691,  -266195706, -1643464018,   901885509,  -956291306])
------------------------dataset/zetyun.csv------------------------
                                 id name     value
0  60dcd6597ac34d97aa2fc913b95009c4  李八搜    873.89
1  537807d539d74d23a497cf7e80b75afa  王三于  15462.63
2  ace97a31c0b34c6cafc8c6cbb76ff49c  吴九引     97.67
3  b01d7b6de97b43eb82ee759da3397852  孙一捷     79.97
4  518b5db5bfc14ecb8bf921c5b417b7c2  吴一捷    782.58
------------------------value------------------------
array([  87389, 1546263,    9767,    7997,   78258])


In [4]:
zetyun.load_dataset(
    assets={
        "zetyun_id": sy.Tensor(ids).private(min_val=float(ids.min()), max_val=float(ids.max()), entities="老赖数据:zetyun:id"),
        "zetyun_value": sy.Tensor(values).private(min_val=float(values.min()), max_val=float(values.max()), entities="老赖数据:zetyun:values")
    },
    name="zetyun",
    description="老赖数据:zetyun"
)


Loading dataset... uploading... SUCCESS!                                                                                                                                      

Run <your client variable>.datasets to see your new dataset loaded into your machine!


In [5]:
zetyun.datasets

In [6]:
id_ptr = zetyun.datasets[0]["zetyun_id"]
print(id_ptr)

array([-1436547945, -1207615334,   630991818, ..., -1021050135,
       -1071826404,  -817110010])

 (The data printed above is synthetic - it's an imitation of the real data.)


In [7]:
id_ptr.request(reason="需要获取准确数据, 准备求交")

In [8]:
zetyun.requests

[<RequestMessage: 12a1d50018524040ab1be1af8e462198>]

In [9]:
[x for x in zetyun.requests.requests if x.request_description == "需要获取准确数据, 准备求交"][0].grant()

In [10]:
# import uuid
# zetyun.requests[str(uuid.UUID("452f60d0f4f54dfb9ec909354f508dad"))]

In [11]:
# zetyun.requests[str(uuid.UUID("452f60d0f4f54dfb9ec909354f508dad"))].grant()

In [10]:
zetyun_id_tensor = id_ptr.get(delete_obj=False)
type(zetyun_id_tensor)

syft.core.tensor.tensor.Tensor

In [11]:
zetyun_id_length = len(zetyun_id_tensor)

In [12]:
scc = sy.login(url="http://172.20.58.117:8081/", email="sample@zetyun.com", password="zetyun")

Connecting to http://172.20.58.117:8081/... done! 	 Logging into scc... done!


In [13]:
scc.store

[array([ 581159927, 1713586481, 1079024742, ...,  465466004, 2001088055,
        447775331])

 (The data printed above is synthetic - it's an imitation of the real data.)]

In [14]:
import openmined_psi as psi
client = psi.client.CreateWithNewKey(True)

In [15]:

sy.lib.python.Int(zetyun_id_length).send(scc, pointable=True, tags=["client_items_len"], description="求交初始化: 请服务器设置好, fpr=1e-6, reveal_intersection=True")

<IntPointer -> scc:c5665845d6bd4ae2b526d9bc5db95353>

In [16]:
scc.store.pandas

ID                Tags  \
0  <UID: 75323e0cb6ed46479ab45e0198ba5b2e>           [#scc_id]   
1  <UID: c5665845d6bd4ae2b526d9bc5db95353>  [client_items_len]   

                                         Description  \
0                                                      
1  求交初始化: 请服务器设置好, fpr=1e-6, reveal_intersection=...   

                                object_type  
0  <class 'syft.core.tensor.tensor.Tensor'>  
1             <class 'syft.lib.python.Int'>

In [19]:
# ls = [x for x in scc.store.store if 'setup' in x.tags]
# ls[0]
# scc.store[ls[0].id_at_location]

In [17]:
scc.store.pandas

ID                Tags  \
0  <UID: 75323e0cb6ed46479ab45e0198ba5b2e>           [#scc_id]   
1  <UID: c5665845d6bd4ae2b526d9bc5db95353>  [client_items_len]   
2  <UID: bf6dbcd68d8942a1b4626d67bdfaa452>             [setup]   

                                         Description  \
0                                                      
1  求交初始化: 请服务器设置好, fpr=1e-6, reveal_intersection=...   
2                                            服务器设置好了   

                                object_type  
0  <class 'syft.core.tensor.tensor.Tensor'>  
1             <class 'syft.lib.python.Int'>  
2       <class 'syft.lib.python.list.List'>

In [18]:
scc.store[2].request(reason="客户端需要初始设置")

In [19]:

setupMsg = scc.store[2].get(delete_obj=False)
setup = psi.ServerSetup()
setup.ParseFromString(setupMsg[0])


10957

In [20]:
client_items = [str(i) for i in zetyun_id_tensor.child.child.tolist()]

In [21]:
request = client.CreateRequest(client_items)
type(request)

private_set_intersection.proto.psi_pb2.Request

In [22]:
msg = request.SerializeToString()
wrapper = sy.lib.python.List()
wrapper.append(msg)
request_ptr = wrapper.send(scc, tags=["request"], pointable=True, description="求交request")

In [25]:
scc.store

[array([-430835515, 1708981127, 1964940059, ..., 2126755318,  480402211,
        959896486])

 (The data printed above is synthetic - it's an imitation of the real data.), <IntPointer -> scc:c5665845d6bd4ae2b526d9bc5db95353>, <ListPointer -> scc:bf6dbcd68d8942a1b4626d67bdfaa452>, <ListPointer -> scc:af32fc69463b4962892a9fd773480fd1>, <ListPointer -> scc:25063f8efbd64d0e863f3329b0c38e39>]

In [26]:
scc.store[4].request(reason="客户端要看结果")

In [27]:
repMsg = scc.store[4].get(delete_obj=False)

In [28]:
response = psi.Response()
response.ParseFromString(repMsg[0])

350000

In [29]:
intersection = client.GetIntersection(setup, response)

In [30]:
len(intersection)

# intersection

2520

In [31]:
#验证结果是否正确
intersected_items = [item for index, item in enumerate(client_items) if index in set(intersection)]


In [32]:
client_items[0:5]

['450007691', '-266195706', '-1643464018', '901885509', '-956291306']

In [33]:
intersected_items[0:5]

['450007691', '901885509', '1372689838', '466742559', '-736305036']

In [35]:
# sy.lib.python.Int(15).send(scc, pointable=True, tags=["test_int"], description="我用来测试int")
# scc.store

In [36]:
# scc.requests

In [34]:
esf = sy.login(url="http://172.20.58.251:8081/", email="sample2@zetyun.com", password="zetyun")

Connecting to http://172.20.58.251:8081/... done! 	 Logging into esf... done!


In [35]:
import inter

psi_client = inter.PsiClient("2nd", esf, True, intersected_items)

In [39]:
# import time
# ls = []
# while True:
#     ls = [x for x in esf.store.store if 'setup' in x.tags]
#     if len(ls) == 0:
#         time.sleep(3)
#     else:
#         break
#
# ls

In [36]:
psi_client.setup()


1. 首先客户端提供 client_items_len
2. 等待服务端 setup
3. 获取 setup 的值


[2021-12-31T16:50:08.443011+0800][CRITICAL][logger]][12424] You do not have permission to .get() Object with ID: <UID: 1a6bda5c308b428087eeaa38ccd9d275> on node esf Please submit a request.


In [37]:
psi_client.setup_info

gcs {
  div: 31
  hash_range: 12600000000000
}
bits: "e\216\323\234\013U\241p\262\315mL Nd\332~\006\200\313\305\277w<dy\275m]\247\034\331F\323@\021J\026\006n\033\340p\001`\350\215:bEw\225\335b6\360\247\273b\240\225\324+\2322%\317\243}%\212\005\031\317\320\344\223\rxo\230\243\300\242,}\346\317\032U\301\321;0\372\017\302S\224\026\352\206\352\230\335{P\337\243={\002{\266?I\213\371\032bl\270\200\332\260\376\337\351c6\014V-\344\375&\225\200Y\360e\352\256\000\310\t\272\361\300:p\312\024\277\213O\203s3\375\355\0062\000\230\023\013\376,d\002.\252\300~@\311S\005\360T\"\232\224w\003eL\316\020\315\317\372V\236t\343G\323=\372\006\037\227\326C\320\\h\023W\t\361\313\333CF\0032\267%|`\223\2201\210t\347\260\230\030/3\001\3328+\251\016\233\316 \313\026Y\r\346 \021q\022U\317\037\231\343\323}\354\220\367\000\256\261\227\345\014t99B\361\252n\017\356m\022\370z\243\366\325\224\325\245\255O4\363c\271>$g\264\263\224\007r\316\000\350\022\232\247\331{\372\020\362\371\030A*\366\311Br\222\030\017\310l@\303P&\362m

In [38]:
_, intersected_items2 = psi_client.intersect()

1. 客户端发送 request
2. 等待服务端返回 response
3. 获取 response


[2021-12-31T16:51:28.908858+0800][CRITICAL][logger]][12424] You do not have permission to .get() Object with ID: <UID: 07390f0bd4074293bc403a90dbd4ce57> on node esf Please submit a request.


4. 计算 intersection


In [39]:
_

1259

In [40]:
intersected_items2[0:5]

['450007691', '466742559', '-1557623790', '-1585423580', '-1966399277']

In [41]:
sub_positions = []
inter_set = set(intersected_items2)
for index, value in enumerate(ids):
    if str(value) in inter_set:
        sub_positions.append(index)


In [42]:

sub_positions

[0,
 8,
 12,
 18,
 22,
 26,
 34,
 38,
 40,
 50,
 60,
 66,
 68,
 84,
 90,
 92,
 94,
 96,
 104,
 106,
 108,
 112,
 118,
 128,
 130,
 140,
 156,
 182,
 188,
 192,
 196,
 202,
 208,
 210,
 214,
 244,
 254,
 306,
 310,
 324,
 326,
 328,
 334,
 350,
 352,
 362,
 372,
 408,
 422,
 430,
 440,
 454,
 456,
 474,
 478,
 482,
 500,
 502,
 510,
 514,
 520,
 528,
 544,
 546,
 550,
 560,
 562,
 566,
 572,
 574,
 586,
 594,
 600,
 602,
 606,
 620,
 628,
 638,
 646,
 650,
 652,
 666,
 668,
 680,
 692,
 702,
 740,
 742,
 744,
 758,
 766,
 774,
 782,
 786,
 800,
 804,
 806,
 824,
 828,
 838,
 844,
 848,
 856,
 862,
 866,
 872,
 876,
 878,
 884,
 888,
 890,
 894,
 896,
 900,
 902,
 906,
 912,
 914,
 936,
 972,
 984,
 990,
 992,
 996,
 1014,
 1016,
 1024,
 1028,
 1034,
 1046,
 1050,
 1052,
 1054,
 1064,
 1066,
 1082,
 1096,
 1100,
 1106,
 1120,
 1124,
 1132,
 1134,
 1142,
 1148,
 1190,
 1200,
 1210,
 1238,
 1242,
 1246,
 1258,
 1260,
 1272,
 1292,
 1302,
 1338,
 1346,
 1356,
 1372,
 1376,
 1378,
 1388,
 13

In [43]:
sub_matrix = []
for i in range(len(intersected_items2)):
    line = []
    for j in range(len(ids)):
        if j == sub_positions[i]:
            line.append(1)
        else:
            line.append(0)
    sub_matrix.append(line)


In [44]:
zetyun_value_ptr = zetyun.datasets[0]["zetyun_value"]
zetyun_value_ptr

array([2180872, 2052307, 9050969, ..., 3962364, 8727695, 9173389])

 (The data printed above is synthetic - it's an imitation of the real data.)

In [45]:
zetyun_value_ptr.request(reason="获取zetyun_value")
[x for x in zetyun.requests.requests if x.request_description == "获取zetyun_value"][0].grant()

In [46]:
zetyun_value_tensor = zetyun_value_ptr.get(delete_obj=False)
zetyun_value = zetyun_value_tensor.child.child
type(zetyun_value)

numpy.ndarray

In [47]:
zetyun_value_tensor.shape

(10000,)

In [48]:
import numpy as np
zetyun_slice = np.array(sub_matrix) @ zetyun_value

In [49]:
# print(np.array(sub_matrix))
# print(type(zetyun_slice))
print(zetyun_slice.shape)
print(zetyun_slice[0:5])

(1259,)
[  87389 8779892   49139 9464883    5450]


In [50]:
sy.lib.python.List(intersected_items2).send(esf, pointable=True, tags=["intersected_items2"], description="intersected_items2")

<ListPointer -> esf:6dc91b0858064227a367c5c3e067a206>

In [51]:
zetyun.users.create(
    **{
        "name": "esf",
        "email": "sample3@zetyun.com",
        "password": "zetyun",
        "budget":200
    }
)

In [52]:
sy.Tensor(zetyun_slice).send(esf, pointable=True, tags=["zetyun_slice"], description="zetyun_slice")

<TensorPointer -> esf:49dcaec9fe0f430fa03d306da86c99fd>